# Form implementation generated from reading ui file 'history_item.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_historyItem(object):
    def setupUi(self, historyItem):
        historyItem.setObjectName("historyItem")
        historyItem.resize(950, 46)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assert/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        historyItem.setWindowIcon(icon)
        historyItem.setStyleSheet("#historyItem {\n"
"border-radius: 16px;\n"
"background-color: #FAFCFD;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.historyItemFrame = QtWidgets.QFrame(parent=historyItem)
        self.historyItemFrame.setGeometry(QtCore.QRect(0, 0, 950, 46))
        self.historyItemFrame.setStyleSheet("#historyItemFrame {\n"
"border-radius: 16px;\n"
"background-color: #FAFCFD;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.historyItemFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.historyItemFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.historyItemFrame.setObjectName("historyItemFrame")
        self.btnDelete = QtWidgets.QPushButton(parent=self.historyItemFrame)
        self.btnDelete.setGeometry(QtCore.QRect(894, 5, 36, 36))
        self.btnDelete.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnDelete.setStyleSheet("QPushButton {\n"
"    color: #FFF;\n"
"    background-color: #FFF;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #E8E8E8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #EBEBEB;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assert/delete_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnDelete.setIcon(icon1)
        self.btnDelete.setIconSize(QtCore.QSize(30, 30))
        self.btnDelete.setObjectName("btnDelete")
        self.btnView = QtWidgets.QPushButton(parent=self.historyItemFrame)
        self.btnView.setGeometry(QtCore.QRect(818, 5, 36, 36))
        self.btnView.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnView.setStyleSheet("QPushButton {\n"
"    color: #FFF;\n"
"    background-color: #FFF;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #E8E8E8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #EBEBEB;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assert/view_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnView.setIcon(icon2)
        self.btnView.setIconSize(QtCore.QSize(30, 30))
        self.btnView.setObjectName("btnView")
        self.btnDownload = QtWidgets.QPushButton(parent=self.historyItemFrame)
        self.btnDownload.setGeometry(QtCore.QRect(742, 5, 36, 36))
        self.btnDownload.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnDownload.setStyleSheet("QPushButton {\n"
"    color: #FFF;\n"
"    background-color: #FFF;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #E8E8E8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #EBEBEB;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assert/download_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnDownload.setIcon(icon3)
        self.btnDownload.setIconSize(QtCore.QSize(100, 100))
        self.btnDownload.setObjectName("btnDownload")
        self.lblAttack = QtWidgets.QLabel(parent=self.historyItemFrame)
        self.lblAttack.setGeometry(QtCore.QRect(20, 13, 200, 20))
        self.lblAttack.setStyleSheet("#lblAttack {\n"
"color: #000;\n"
"font-family: Inter;\n"
"font-size: 16px;\n"
"font-style: normal;\n"
"font-weight: 450;\n"
"line-height: normal;\n"
"background-color: transparent;\n"
"border-color :transparent;\n"
"}")
        self.lblAttack.setObjectName("lblAttack")
        self.lblDate = QtWidgets.QLabel(parent=self.historyItemFrame)
        self.lblDate.setGeometry(QtCore.QRect(325, 13, 150, 20))
        self.lblDate.setStyleSheet("#lblDate {\n"
"color: #000;\n"
"font-family: Inter;\n"
"font-size: 16px;\n"
"font-style: normal;\n"
"font-weight: 450;\n"
"line-height: normal;\n"
"background-color: transparent;\n"
"border-color :transparent;\n"
"}")
        self.lblDate.setObjectName("lblDate")
        self.lblTime = QtWidgets.QLabel(parent=self.historyItemFrame)
        self.lblTime.setGeometry(QtCore.QRect(550, 13, 150, 20))
        self.lblTime.setStyleSheet("#lblTime {\n"
"color: #000;\n"
"font-family: Inter;\n"
"font-size: 16px;\n"
"font-style: normal;\n"
"font-weight: 450;\n"
"line-height: normal;\n"
"background-color: transparent;\n"
"border-color :transparent;\n"
"}")
        self.lblTime.setObjectName("lblTime")

        self.retranslateUi(historyItem)
        QtCore.QMetaObject.connectSlotsByName(historyItem)

    def retranslateUi(self, historyItem):
        _translate = QtCore.QCoreApplication.translate
        historyItem.setWindowTitle(_translate("historyItem", "Item"))
        self.lblAttack.setText(_translate("historyItem", "Attack Label"))
        self.lblDate.setText(_translate("historyItem", "2024-01-07"))
        self.lblTime.setText(_translate("historyItem", "11:19:28"))
