# Form implementation generated from reading ui file 'history_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_historyForm(object):
    def setupUi(self, historyForm):
        historyForm.setObjectName("historyForm")
        historyForm.resize(990, 650)
        historyForm.setMinimumSize(QtCore.QSize(990, 650))
        historyForm.setMaximumSize(QtCore.QSize(990, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assert/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        historyForm.setWindowIcon(icon)
        historyForm.setStyleSheet("#historyForm {\n"
"border-radius: 16px;\n"
"background: #FFF;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.recordsFrame = QtWidgets.QFrame(parent=historyForm)
        self.recordsFrame.setGeometry(QtCore.QRect(10, 62, 970, 335))
        self.recordsFrame.setStyleSheet("#recordsFrame {\n"
"border-radius: 10px;\n"
"background: #D9DEE2;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.recordsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.recordsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.recordsFrame.setObjectName("recordsFrame")
        self.recordsListWidget = QtWidgets.QListWidget(parent=self.recordsFrame)
        self.recordsListWidget.setGeometry(QtCore.QRect(0, 0, 970, 335))
        self.recordsListWidget.setStyleSheet("QListWidget {\n"
"border-radius: 10px;\n"
"background: #D9DEE2;\n"
"border: 1px solid #dddddd;\n"
"margin: 10px\n"
"}")
        self.recordsListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.recordsListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.recordsListWidget.setObjectName("recordsListWidget")
        self.detailFrame = QtWidgets.QFrame(parent=historyForm)
        self.detailFrame.setGeometry(QtCore.QRect(10, 407, 970, 233))
        self.detailFrame.setStyleSheet("#detailFrame {\n"
"border-radius: 10px;\n"
"background: #FFF;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.detailFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.detailFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.detailFrame.setObjectName("detailFrame")
        self.historyLabelFrame = QtWidgets.QFrame(parent=historyForm)
        self.historyLabelFrame.setGeometry(QtCore.QRect(10, 10, 970, 42))
        self.historyLabelFrame.setStyleSheet("#historyLabelFrame {\n"
"border-radius: 10px;\n"
"background: #5380A0;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.historyLabelFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.historyLabelFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.historyLabelFrame.setObjectName("historyLabelFrame")
        self.lblHistory = QtWidgets.QLabel(parent=self.historyLabelFrame)
        self.lblHistory.setGeometry(QtCore.QRect(10, 0, 101, 42))
        self.lblHistory.setStyleSheet("QLabel {\n"
"color: #FFF;\n"
"font-family: Inter;\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"background-color: transparent;\n"
"border-color :transparent;\n"
"}")
        self.lblHistory.setObjectName("lblHistory")

        self.retranslateUi(historyForm)
        QtCore.QMetaObject.connectSlotsByName(historyForm)

    def retranslateUi(self, historyForm):
        _translate = QtCore.QCoreApplication.translate
        historyForm.setWindowTitle(_translate("historyForm", "History"))
        self.lblHistory.setText(_translate("historyForm", "History"))
