# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1190, 670)
        mainWindow.setMinimumSize(QtCore.QSize(1190, 670))
        mainWindow.setMaximumSize(QtCore.QSize(1190, 670))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assert/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet("QMainWindow{\n"
"background: #EAEAEA;\n"
"}")
        self.centralWidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralWidget.setStyleSheet("QWidget {\n"
"background: #EAEAEA;\n"
"}")
        self.centralWidget.setObjectName("centralWidget")
        self.navFrame = QtWidgets.QFrame(parent=self.centralWidget)
        self.navFrame.setGeometry(QtCore.QRect(10, 10, 170, 650))
        self.navFrame.setStyleSheet("QFrame {\n"
"border-radius: 16px;\n"
"background: #FFF;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.navFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.navFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.navFrame.setObjectName("navFrame")
        self.statusFrame = QtWidgets.QFrame(parent=self.navFrame)
        self.statusFrame.setGeometry(QtCore.QRect(10, 10, 150, 150))
        self.statusFrame.setStyleSheet("QFrame {\n"
"border-radius: 10px;\n"
"background: #FFF;\n"
"border: 1px solid #E8E8E8;\n"
"}")
        self.statusFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.statusFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.statusFrame.setObjectName("statusFrame")
        self.btnStatus = QtWidgets.QPushButton(parent=self.statusFrame)
        self.btnStatus.setGeometry(QtCore.QRect(0, 0, 150, 150))
        self.btnStatus.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnStatus.setStyleSheet("QPushButton {\n"
"    color: #FFF;\n"
"    background-color: #FFF;\n"
"    border-radius: 10px;\n"
"    border: 1px solid #E8E8E8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #EBEBEB;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assert/status_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnStatus.setIcon(icon1)
        self.btnStatus.setIconSize(QtCore.QSize(100, 100))
        self.btnStatus.setObjectName("btnStatus")
        self.lblStatus = QtWidgets.QLabel(parent=self.statusFrame)
        self.lblStatus.setGeometry(QtCore.QRect(50, 120, 51, 16))
        self.lblStatus.setStyleSheet("#lblStatus {\n"
"    font-family: Inter;\n"
"    font-size: 16px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"    background-color: transparent;\n"
"    border-color :transparent;\n"
"}")
        self.lblStatus.setObjectName("lblStatus")
        self.historyFrame = QtWidgets.QFrame(parent=self.navFrame)
        self.historyFrame.setGeometry(QtCore.QRect(10, 170, 150, 150))
        self.historyFrame.setStyleSheet("QFrame {\n"
"border-radius: 10px;\n"
"background: #FFF;\n"
"border: 1px solid #E8E8E8;\n"
"}")
        self.historyFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.historyFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.historyFrame.setObjectName("historyFrame")
        self.btnHistory = QtWidgets.QPushButton(parent=self.historyFrame)
        self.btnHistory.setGeometry(QtCore.QRect(0, 0, 150, 150))
        self.btnHistory.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnHistory.setStyleSheet("QPushButton {\n"
"    color: #FFF;\n"
"    background-color: #FFF;\n"
"    border-radius: 10px;\n"
"    border: 1px solid #E8E8E8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #EBEBEB;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assert/hisotry_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnHistory.setIcon(icon2)
        self.btnHistory.setIconSize(QtCore.QSize(100, 100))
        self.btnHistory.setObjectName("btnHistory")
        self.lblHistory = QtWidgets.QLabel(parent=self.historyFrame)
        self.lblHistory.setGeometry(QtCore.QRect(45, 120, 61, 21))
        self.lblHistory.setStyleSheet("#lblHistory {\n"
"    font-family: Inter;\n"
"    font-size: 16px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"    background-color: transparent;\n"
"    border-color :transparent;\n"
"}")
        self.lblHistory.setObjectName("lblHistory")
        self.scanFrame = QtWidgets.QFrame(parent=self.navFrame)
        self.scanFrame.setGeometry(QtCore.QRect(10, 330, 150, 150))
        self.scanFrame.setStyleSheet("QFrame {\n"
"border-radius: 10px;\n"
"background: #FFF;\n"
"border: 1px solid #E8E8E8;\n"
"}")
        self.scanFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.scanFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.scanFrame.setObjectName("scanFrame")
        self.btnScan = QtWidgets.QPushButton(parent=self.scanFrame)
        self.btnScan.setGeometry(QtCore.QRect(0, 0, 150, 150))
        self.btnScan.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnScan.setStyleSheet("QPushButton {\n"
"    color: #FFF;\n"
"    background-color: #FFF;\n"
"    border-radius: 10px;\n"
"    border: 1px solid #E8E8E8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #EBEBEB;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assert/scan_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnScan.setIcon(icon3)
        self.btnScan.setIconSize(QtCore.QSize(100, 100))
        self.btnScan.setObjectName("btnScan")
        self.lblScan = QtWidgets.QLabel(parent=self.scanFrame)
        self.lblScan.setGeometry(QtCore.QRect(50, 120, 41, 16))
        self.lblScan.setStyleSheet("#lblScan {\n"
"    font-family: Inter;\n"
"    font-size: 16px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"    background-color: transparent;\n"
"    border-color :transparent;\n"
"}")
        self.lblScan.setObjectName("lblScan")
        self.settingsFrame = QtWidgets.QFrame(parent=self.navFrame)
        self.settingsFrame.setGeometry(QtCore.QRect(10, 490, 150, 150))
        self.settingsFrame.setStyleSheet("QFrame {\n"
"border-radius: 10px;\n"
"background: #FFF;\n"
"border: 1px solid #E8E8E8;\n"
"}")
        self.settingsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.settingsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.settingsFrame.setObjectName("settingsFrame")
        self.btnSettings = QtWidgets.QPushButton(parent=self.settingsFrame)
        self.btnSettings.setGeometry(QtCore.QRect(0, 0, 150, 150))
        self.btnSettings.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSettings.setStyleSheet("QPushButton {\n"
"    color: #FFF;\n"
"    background-color: #FFF;\n"
"    border-radius: 10px;\n"
"    border: 1px solid #E8E8E8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #EBEBEB;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("assert/settings_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSettings.setIcon(icon4)
        self.btnSettings.setIconSize(QtCore.QSize(100, 100))
        self.btnSettings.setObjectName("btnSettings")
        self.lblSettings = QtWidgets.QLabel(parent=self.settingsFrame)
        self.lblSettings.setGeometry(QtCore.QRect(45, 120, 63, 21))
        self.lblSettings.setStyleSheet("#lblSettings {\n"
"    font-family: Inter;\n"
"    font-size: 16px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"    background-color: transparent;\n"
"    border-color :transparent;\n"
"}")
        self.lblSettings.setObjectName("lblSettings")
        self.mainFrame = QtWidgets.QFrame(parent=self.centralWidget)
        self.mainFrame.setGeometry(QtCore.QRect(190, 10, 990, 650))
        self.mainFrame.setStyleSheet("#mainFrame {\n"
"border-radius: 16px;\n"
"background: #FFF;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFrame.setObjectName("mainFrame")
        mainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "GuardianNet"))
        self.lblStatus.setText(_translate("mainWindow", "Status"))
        self.lblHistory.setText(_translate("mainWindow", "History"))
        self.lblScan.setText(_translate("mainWindow", "Scan"))
        self.lblSettings.setText(_translate("mainWindow", "Settings"))
