# Form implementation generated from reading ui file 'scan_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_scanForm(object):
    def setupUi(self, scanForm):
        scanForm.setObjectName("scanForm")
        scanForm.resize(990, 650)
        scanForm.setMinimumSize(QtCore.QSize(990, 650))
        scanForm.setMaximumSize(QtCore.QSize(990, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assert/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        scanForm.setWindowIcon(icon)
        scanForm.setStyleSheet("#scanForm {\n"
"border-radius: 16px;\n"
"background: #FFF;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.manualScanFrame = QtWidgets.QFrame(parent=scanForm)
        self.manualScanFrame.setGeometry(QtCore.QRect(10, 62, 970, 233))
        self.manualScanFrame.setStyleSheet("#manualScanFrame {\n"
"border-radius: 10px;\n"
"background: #D9DEE2;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.manualScanFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.manualScanFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.manualScanFrame.setObjectName("manualScanFrame")
        self.btnRunScan = QtWidgets.QPushButton(parent=self.manualScanFrame)
        self.btnRunScan.setEnabled(True)
        self.btnRunScan.setGeometry(QtCore.QRect(410, 120, 150, 35))
        self.btnRunScan.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnRunScan.setStyleSheet("QPushButton {\n"
"    color: #FFF;\n"
"    background-color: #2C6331;\n"
"    font-family: Inter;\n"
"    font-size: 16px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(64, 145, 71);\n"
"}")
        self.btnRunScan.setObjectName("btnRunScan")
        self.lblPcapFile = QtWidgets.QLabel(parent=self.manualScanFrame)
        self.lblPcapFile.setGeometry(QtCore.QRect(10, 25, 100, 31))
        self.lblPcapFile.setStyleSheet("QLabel {\n"
"color: #000;\n"
"font-family: Inter;\n"
"font-size: 16px;\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"line-height: normal;\n"
"background-color: transparent;\n"
"border-color :transparent;\n"
"}")
        self.lblPcapFile.setObjectName("lblPcapFile")
        self.lblOutput = QtWidgets.QLabel(parent=self.manualScanFrame)
        self.lblOutput.setGeometry(QtCore.QRect(10, 65, 100, 31))
        self.lblOutput.setStyleSheet("QLabel {\n"
"color: #000;\n"
"font-family: Inter;\n"
"font-size: 16px;\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"line-height: normal;\n"
"background-color: transparent;\n"
"border-color :transparent;\n"
"}")
        self.lblOutput.setObjectName("lblOutput")
        self.txtPcapFilePath = QtWidgets.QLineEdit(parent=self.manualScanFrame)
        self.txtPcapFilePath.setGeometry(QtCore.QRect(130, 30, 500, 27))
        self.txtPcapFilePath.setStyleSheet("#txtPcapFilePath {\n"
"    border-radius: 5px;\n"
"    border: 1px solid #B7B7B7;\n"
"    background: #FFFFFF;\n"
"    color: #000;\n"
"    font-family: Inter;\n"
"    font-size: 14px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"}\n"
"\n"
"#txtPcapFilePath::focus {\n"
"    border: 1px solid #4383CD;\n"
"}")
        self.txtPcapFilePath.setObjectName("txtPcapFilePath")
        self.txtOutputFilePath = QtWidgets.QLineEdit(parent=self.manualScanFrame)
        self.txtOutputFilePath.setGeometry(QtCore.QRect(130, 70, 500, 27))
        self.txtOutputFilePath.setStyleSheet("#txtOutputFilePath {\n"
"    border-radius: 5px;\n"
"    border: 1px solid #B7B7B7;\n"
"    background: #FFFFFF;\n"
"    color: #000;\n"
"    font-family: Inter;\n"
"    font-size: 14px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"}\n"
"\n"
"#txtOutputFilePath::focus {\n"
"    border: 1px solid #4383CD;\n"
"}")
        self.txtOutputFilePath.setObjectName("txtOutputFilePath")
        self.btnOpenFile = QtWidgets.QPushButton(parent=self.manualScanFrame)
        self.btnOpenFile.setEnabled(True)
        self.btnOpenFile.setGeometry(QtCore.QRect(650, 30, 110, 27))
        self.btnOpenFile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnOpenFile.setStyleSheet("QPushButton {\n"
"    color: #FFF;\n"
"    background-color: #3C8B9D;\n"
"    font-family: Inter;\n"
"    font-size: 16px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(69, 161, 182);\n"
"}")
        self.btnOpenFile.setObjectName("btnOpenFile")
        self.btnBrowse = QtWidgets.QPushButton(parent=self.manualScanFrame)
        self.btnBrowse.setEnabled(True)
        self.btnBrowse.setGeometry(QtCore.QRect(650, 70, 110, 27))
        self.btnBrowse.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnBrowse.setStyleSheet("QPushButton {\n"
"    color: #FFF;\n"
"    background-color: #3C8B9D;\n"
"    font-family: Inter;\n"
"    font-size: 16px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(69, 161, 182);\n"
"}")
        self.btnBrowse.setObjectName("btnBrowse")
        self.scanProgressBar = QtWidgets.QProgressBar(parent=self.manualScanFrame)
        self.scanProgressBar.setGeometry(QtCore.QRect(235, 179, 500, 30))
        self.scanProgressBar.setStyleSheet("QProgressBar{\n"
"    border: 1px solid #B7B7B7;\n"
"    background: #FFFFFF;\n"
"    text-align: center;\n"
"}")
        self.scanProgressBar.setProperty("value", 0)
        self.scanProgressBar.setObjectName("scanProgressBar")
        self.chartFrame = QtWidgets.QFrame(parent=scanForm)
        self.chartFrame.setGeometry(QtCore.QRect(10, 305, 970, 335))
        self.chartFrame.setStyleSheet("#chartFrame {\n"
"border-radius: 10px;\n"
"background: #FFF;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.chartFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.chartFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.chartFrame.setObjectName("chartFrame")
        self.scanLabelFrame = QtWidgets.QFrame(parent=scanForm)
        self.scanLabelFrame.setGeometry(QtCore.QRect(10, 10, 970, 42))
        self.scanLabelFrame.setStyleSheet("#scanLabelFrame {\n"
"border-radius: 10px;\n"
"background: #5380A0;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.scanLabelFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.scanLabelFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.scanLabelFrame.setObjectName("scanLabelFrame")
        self.lblScan = QtWidgets.QLabel(parent=self.scanLabelFrame)
        self.lblScan.setGeometry(QtCore.QRect(10, 0, 101, 42))
        self.lblScan.setStyleSheet("QLabel {\n"
"color: #FFF;\n"
"font-family: Inter;\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"background-color: transparent;\n"
"border-color :transparent;\n"
"}")
        self.lblScan.setObjectName("lblScan")

        self.retranslateUi(scanForm)
        QtCore.QMetaObject.connectSlotsByName(scanForm)
        scanForm.setTabOrder(self.txtPcapFilePath, self.txtOutputFilePath)
        scanForm.setTabOrder(self.txtOutputFilePath, self.btnOpenFile)
        scanForm.setTabOrder(self.btnOpenFile, self.btnBrowse)
        scanForm.setTabOrder(self.btnBrowse, self.btnRunScan)

    def retranslateUi(self, scanForm):
        _translate = QtCore.QCoreApplication.translate
        scanForm.setWindowTitle(_translate("scanForm", "Scan"))
        self.btnRunScan.setText(_translate("scanForm", "Run Scan"))
        self.lblPcapFile.setText(_translate("scanForm", "Pcap file:"))
        self.lblOutput.setText(_translate("scanForm", "Output"))
        self.btnOpenFile.setText(_translate("scanForm", "Open File"))
        self.btnBrowse.setText(_translate("scanForm", "Browse"))
        self.lblScan.setText(_translate("scanForm", "Scan"))
