# Form implementation generated from reading ui file 'settings_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_settingsForm(object):
    def setupUi(self, settingsForm):
        settingsForm.setObjectName("settingsForm")
        settingsForm.resize(990, 650)
        settingsForm.setMinimumSize(QtCore.QSize(990, 650))
        settingsForm.setMaximumSize(QtCore.QSize(990, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assert/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        settingsForm.setWindowIcon(icon)
        settingsForm.setStyleSheet("#settingsForm {\n"
"border-radius: 16px;\n"
"background: #FFF;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.changePasswordFrame = QtWidgets.QFrame(parent=settingsForm)
        self.changePasswordFrame.setGeometry(QtCore.QRect(10, 62, 970, 233))
        self.changePasswordFrame.setStyleSheet("#changePasswordFrame {\n"
"border-radius: 10px;\n"
"background: #F6F6E7;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.changePasswordFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.changePasswordFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.changePasswordFrame.setObjectName("changePasswordFrame")
        self.lblChangePassword = QtWidgets.QLabel(parent=self.changePasswordFrame)
        self.lblChangePassword.setGeometry(QtCore.QRect(10, 10, 180, 42))
        self.lblChangePassword.setStyleSheet("QLabel {\n"
"color: #000;\n"
"font-family: Inter;\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"line-height: normal;\n"
"background-color: transparent;\n"
"border-color :transparent;\n"
"}")
        self.lblChangePassword.setObjectName("lblChangePassword")
        self.txtPassword = QtWidgets.QLineEdit(parent=self.changePasswordFrame)
        self.txtPassword.setGeometry(QtCore.QRect(180, 60, 250, 27))
        self.txtPassword.setStyleSheet("#txtPassword {\n"
"    border-radius: 5px;\n"
"    border: 1px solid #B7B7B7;\n"
"    background: #FFFFFF;\n"
"    color: #000;\n"
"    font-family: Inter;\n"
"    font-size: 14px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"}\n"
"\n"
"#txtPassword::focus {\n"
"    border: 1px solid #4383CD;\n"
"}")
        self.txtPassword.setFrame(True)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setPlaceholderText("")
        self.txtPassword.setObjectName("txtPassword")
        self.btnUpdatePassword = QtWidgets.QPushButton(parent=self.changePasswordFrame)
        self.btnUpdatePassword.setEnabled(True)
        self.btnUpdatePassword.setGeometry(QtCore.QRect(350, 150, 150, 35))
        self.btnUpdatePassword.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnUpdatePassword.setStyleSheet("QPushButton {\n"
"    color: #FFF;\n"
"    background-color: #2973A9;\n"
"    font-family: Inter;\n"
"    font-size: 16px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(46, 129, 188);\n"
"}")
        self.btnUpdatePassword.setObjectName("btnUpdatePassword")
        self.lblPassword = QtWidgets.QLabel(parent=self.changePasswordFrame)
        self.lblPassword.setGeometry(QtCore.QRect(10, 60, 101, 31))
        self.lblPassword.setStyleSheet("QLabel {\n"
"color: #000;\n"
"font-family: Inter;\n"
"font-size: 16px;\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"line-height: normal;\n"
"background-color: transparent;\n"
"border-color :transparent;\n"
"}")
        self.lblPassword.setObjectName("lblPassword")
        self.lblConfirmPassword = QtWidgets.QLabel(parent=self.changePasswordFrame)
        self.lblConfirmPassword.setGeometry(QtCore.QRect(10, 100, 160, 31))
        self.lblConfirmPassword.setStyleSheet("QLabel {\n"
"color: #000;\n"
"font-family: Inter;\n"
"font-size: 16px;\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"line-height: normal;\n"
"background-color: transparent;\n"
"border-color :transparent;\n"
"}")
        self.lblConfirmPassword.setObjectName("lblConfirmPassword")
        self.txtConfirmPassword = QtWidgets.QLineEdit(parent=self.changePasswordFrame)
        self.txtConfirmPassword.setGeometry(QtCore.QRect(180, 100, 250, 27))
        self.txtConfirmPassword.setStyleSheet("#txtConfirmPassword {\n"
"    border-radius: 5px;\n"
"    border: 1px solid #B7B7B7;\n"
"    background: #FFFFFF;\n"
"    color: #000;\n"
"    font-family: Inter;\n"
"    font-size: 14px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"}\n"
"\n"
"#txtConfirmPassword::focus {\n"
"    border: 1px solid #4383CD;\n"
"}")
        self.txtConfirmPassword.setFrame(True)
        self.txtConfirmPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtConfirmPassword.setPlaceholderText("")
        self.txtConfirmPassword.setObjectName("txtConfirmPassword")
        self.configFrame = QtWidgets.QFrame(parent=settingsForm)
        self.configFrame.setGeometry(QtCore.QRect(10, 305, 970, 335))
        self.configFrame.setStyleSheet("#configFrame {\n"
"border-radius: 10px;\n"
"background: #EFEAE7;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.configFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.configFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.configFrame.setObjectName("configFrame")
        self.lblBatchSize = QtWidgets.QLabel(parent=self.configFrame)
        self.lblBatchSize.setGeometry(QtCore.QRect(10, 60, 170, 31))
        self.lblBatchSize.setStyleSheet("QLabel {\n"
"color: #000;\n"
"font-family: Inter;\n"
"font-size: 16px;\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"line-height: normal;\n"
"background-color: transparent;\n"
"border-color :transparent;\n"
"}")
        self.lblBatchSize.setObjectName("lblBatchSize")
        self.lblNetworkInterface = QtWidgets.QLabel(parent=self.configFrame)
        self.lblNetworkInterface.setGeometry(QtCore.QRect(10, 100, 170, 31))
        self.lblNetworkInterface.setStyleSheet("QLabel {\n"
"color: #000;\n"
"font-family: Inter;\n"
"font-size: 16px;\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"line-height: normal;\n"
"background-color: transparent;\n"
"border-color :transparent;\n"
"}")
        self.lblNetworkInterface.setObjectName("lblNetworkInterface")
        self.lblChangeConfigurations = QtWidgets.QLabel(parent=self.configFrame)
        self.lblChangeConfigurations.setGeometry(QtCore.QRect(10, 10, 220, 42))
        self.lblChangeConfigurations.setStyleSheet("QLabel {\n"
"color: #000;\n"
"font-family: Inter;\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"line-height: normal;\n"
"background-color: transparent;\n"
"border-color :transparent;\n"
"}")
        self.lblChangeConfigurations.setObjectName("lblChangeConfigurations")
        self.btnUpdateConfig = QtWidgets.QPushButton(parent=self.configFrame)
        self.btnUpdateConfig.setEnabled(True)
        self.btnUpdateConfig.setGeometry(QtCore.QRect(350, 150, 150, 35))
        self.btnUpdateConfig.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnUpdateConfig.setStyleSheet("QPushButton {\n"
"    color: #FFF;\n"
"    background-color: #2973A9;\n"
"    font-family: Inter;\n"
"    font-size: 16px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    line-height: normal;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(46, 129, 188);\n"
"}")
        self.btnUpdateConfig.setObjectName("btnUpdateConfig")
        self.cmbBatchSize = QtWidgets.QComboBox(parent=self.configFrame)
        self.cmbBatchSize.setGeometry(QtCore.QRect(180, 60, 250, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmbBatchSize.setFont(font)
        self.cmbBatchSize.setStyleSheet("#cmbBatchSize {\n"
"    border: 1px solid #B7B7B7;\n"
"    border-radius: 5px;\n"
"    padding-left: 10px;\n"
"    background: #FFFFFF;\n"
"}\n"
"\n"
"#cmbBatchSize::drop-down {\n"
"    border: 0px;\n"
"}\n"
"\n"
"#cmbBatchSize::down-arrow {\n"
"    image: url(assert/comboBox_arrow.ico);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    margin-right:15px;\n"
"}\n"
"\n"
"#cmbBatchSize:on {\n"
"     border: 1px solid #4383CD;\n"
" }\n"
"\n"
"#cmbBatchSize QListView {\n"
"    font-size: 12px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    padding:5px;\n"
"    background-color: #fff;\n"
"    outline: 0px;\n"
"    border-radius: 0;\n"
"}\n"
"\n"
"#cmbBatchSize QListView::item{\n"
"    padding-left:10px;\n"
"    background-color:#FFFFFF;\n"
"}\n"
"\n"
"#cmbBatchSize QListView::item:hover{\n"
"   background-color:#1e90ff;\n"
"}\n"
"\n"
"#cmbBatchSize QListView::item:selected{\n"
"   background-color:#1e90ff;\n"
"}")
        self.cmbBatchSize.setObjectName("cmbBatchSize")
        self.cmbNetworkInterface = QtWidgets.QComboBox(parent=self.configFrame)
        self.cmbNetworkInterface.setGeometry(QtCore.QRect(180, 100, 250, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmbNetworkInterface.setFont(font)
        self.cmbNetworkInterface.setStyleSheet("#cmbNetworkInterface {\n"
"    border: 1px solid #B7B7B7;\n"
"    border-radius: 5px;\n"
"    padding-left: 10px;\n"
"    background: #FFFFFF;\n"
"}\n"
"\n"
"#cmbNetworkInterface::drop-down {\n"
"    border: 0px;\n"
"}\n"
"\n"
"#cmbNetworkInterface::down-arrow {\n"
"    image: url(assert/comboBox_arrow.ico);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"    margin-right:15px;\n"
"}\n"
"\n"
"#cmbNetworkInterface:on {\n"
"     border: 1px solid #4383CD;\n"
" }\n"
"\n"
"#cmbNetworkInterface QListView {\n"
"    font-size: 12px;\n"
"    border:1px solid rgba(0,0,0,10%);\n"
"    padding:5px;\n"
"    background-color: #fff;\n"
"    outline: 0px;\n"
"    border-radius: 0;\n"
"}\n"
"\n"
"#cmbNetworkInterface QListView::item{\n"
"    padding-left:10px;\n"
"    background-color:#FFFFFF;\n"
"}\n"
"\n"
"#cmbNetworkInterface QListView::item:hover{\n"
"   background-color:#1e90ff;\n"
"}\n"
"\n"
"#cmbNetworkInterface QListView::item:selected{\n"
"   background-color:#1e90ff;\n"
"}")
        self.cmbNetworkInterface.setObjectName("cmbNetworkInterface")
        self.settingLabelFrame = QtWidgets.QFrame(parent=settingsForm)
        self.settingLabelFrame.setGeometry(QtCore.QRect(10, 10, 970, 42))
        self.settingLabelFrame.setStyleSheet("#settingLabelFrame {\n"
"border-radius: 10px;\n"
"background: #5380A0;\n"
"border: 1px solid #dddddd;\n"
"}")
        self.settingLabelFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.settingLabelFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.settingLabelFrame.setObjectName("settingLabelFrame")
        self.lblSettings = QtWidgets.QLabel(parent=self.settingLabelFrame)
        self.lblSettings.setGeometry(QtCore.QRect(10, 0, 165, 42))
        self.lblSettings.setStyleSheet("QLabel {\n"
"color: #FFF;\n"
"font-family: Inter;\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"line-height: normal;\n"
"background-color: transparent;\n"
"border-color :transparent;\n"
"}")
        self.lblSettings.setObjectName("lblSettings")

        self.retranslateUi(settingsForm)
        QtCore.QMetaObject.connectSlotsByName(settingsForm)
        settingsForm.setTabOrder(self.txtPassword, self.txtConfirmPassword)
        settingsForm.setTabOrder(self.txtConfirmPassword, self.btnUpdatePassword)
        settingsForm.setTabOrder(self.btnUpdatePassword, self.cmbBatchSize)
        settingsForm.setTabOrder(self.cmbBatchSize, self.cmbNetworkInterface)
        settingsForm.setTabOrder(self.cmbNetworkInterface, self.btnUpdateConfig)

    def retranslateUi(self, settingsForm):
        _translate = QtCore.QCoreApplication.translate
        settingsForm.setWindowTitle(_translate("settingsForm", "Settings"))
        self.lblChangePassword.setText(_translate("settingsForm", "Change Password"))
        self.btnUpdatePassword.setText(_translate("settingsForm", "Update"))
        self.lblPassword.setText(_translate("settingsForm", "Password:"))
        self.lblConfirmPassword.setText(_translate("settingsForm", "Confirm Password:"))
        self.lblBatchSize.setText(_translate("settingsForm", "Packets batch size:"))
        self.lblNetworkInterface.setText(_translate("settingsForm", "Network interface:"))
        self.lblChangeConfigurations.setText(_translate("settingsForm", "Change Configurations"))
        self.btnUpdateConfig.setText(_translate("settingsForm", "Update"))
        self.lblSettings.setText(_translate("settingsForm", "System Settings"))
